modLoader="kotlinforforge" #mandatory
loaderVersion="[3,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/Sreeraj-S/PokemonToItem/issues"

[[mods]] #mandatory
modId="pokemontoitem" #mandatory
version="${version}" #mandatory
displayName="Pokemon To Item" #mandatory
displayURL="https://github.com/Sreeraj-S"
#logoFile="examplemod.png" #optional
credits="Thanks to the Cobblemon Community."
authors="Sreeraj"
description='''
 Adds special commands to pokemontoitem
'''

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.pokemontoitem]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"

[[dependencies.pokemontoitem]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[40,)" #mandatory

[[dependencies.pokemontoitem]]
modId="architectury"
mandatory=true
versionRange="[6.5.69,)"